name: PHP_CodeSniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: curl,mbstring,intl,mongodb
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs
